# Generated by Django 5.1.2 on 2024-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_youtubeshort_watchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubeshort",
            name="user_email",
            field=models.CharField(default="example@gmail.com", max_length=100),
            preserve_default=False,
        ),
    ]
